%% AstiBesselPSF.m
% The AstiBesselPSF.m calculates the Bessel PSF (Z=0) generated by a high NA
% objective (NA 0.7) with non-circularly symmetrical aberrations.
folder = fileparts(which(mfilename)); 
addpath(genpath(folder));
ResultPath=[folder '\bessel_0.05xy_z0\'];
if ~exist(ResultPath, 'dir')
   mkdir(ResultPath)
end
%% parameters
SLM.pitch=15; %um
SLM.pixelNumber=512;
SLM.size=SLM.pitch*SLM.pixelNumber; %um
upper_bound=255;  %gray level range
lower_bound=0;
delta_degree=2*pi/(upper_bound-lower_bound);
laser_sig=3.262; %mm
refind=1.33;
lambda=940*1e-3; %um
global obj;
obj.mag=25;
obj.NA=1.05;
obj.f=180/obj.mag; %mm in air
obj.D=2*obj.f*obj.NA; %mm
mag=2; %magnification
k=2*pi/lambda; %um^-1

%% field at back pupil plane
[File,FilePath] = uigetfile('*.bmp');
phase=imread([FilePath File],'bmp');
% phase=imread("Astigmatism.bmp");
[pixel_num,~]=size(phase);
phase=2*pi/255*double(phase)-pi;

field_x=(-pixel_num/2:pixel_num/2-1)*SLM.pitch*2;
field_y=(-pixel_num/2:pixel_num/2-1)*SLM.pitch*2; 

field_x2=min(field_x):10:max(field_x); %um
field_y2=min(field_y):10:max(field_y);
[field_xx2,field_yy2]=meshgrid(field_x2,field_y2);
field_rr2=sqrt(field_xx2.^2+field_yy2.^2);

phase2=interp2(field_xx,field_yy,phase,field_xx2,field_yy2);

intensity2=zeros(length(field_x2));
intensity2(field_rr2>4970&field_rr2<5270)=1;%NA=0.7, R1

field2=intensity2.*exp(1.j*phase2);



%% calc PSF
x=-1.5:0.05:1.5; 
y=-1.5:0.05:1.5;
z=0;

    PSF=Calc_Annular_Field_Integrals(x, y, z(a),field2, field_x2*1e-3, field_y2*1e-3, lambda,refind,obj.f);
    PSF=uint16(squeeze(PSF)*1e-9);
    imwrite(PSF,[ResultPath,num2str(z(a)),'.tif'])